Ruby/moodBoard/config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :comments

  resources :designs

end

Ruby/moodBoard/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :design
end

Ruby/moodBoard/app/models/design.rb
class Design < ActiveRecord::Base
	has_many :comments

	has_attached_file :photo, 
		:styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates_attachment :photo, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }


end

		# :storage => :s3,
		# :s3_credentials => File.join(Rails.root, 'config', 'amazonS3.yml'),
		# :s3_host_alias => 'http://s3-sa-east-1.amazonaws.com/experiments.moodboard',
		# :s3_url_options => ':CNAME'

Ruby/moodBoard/app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments

end

Ruby/moodBoard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby/moodBoard/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :design_id)
    end
end

Ruby/moodBoard/app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design.destroy
    respond_to do |format|
      format.html { redirect_to designs_url, notice: 'Design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:title, :photo)
    end
end

Ruby/moodBoard/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

Ruby/moodBoard/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/moodBoard/app/helpers/comments_helper.rb
module CommentsHelper
end

Ruby/moodBoard/app/helpers/designs_helper.rb
module DesignsHelper
end

Ruby/moodBoard/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/moodBoard/app/views/comments/_form.html.haml
= form_for(@comment) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :content
    %br/
    = f.text_area :content
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .field
    = f.label :design_id
    %br/
    = f.text_field :design_id
  .actions
    = f.submit

Ruby/moodBoard/app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form'
= link_to 'Show', @comment
|
= link_to 'Back', comments_path

Ruby/moodBoard/app/views/comments/index.html.haml
%p#notice= notice
%h1 Listing Comments
%table
  %thead
    %tr
      %th Content
      %th User
      %th Design
      %th{:colspan => "3"}
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.content
        %td= comment.user
        %td= comment.design
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_comment_path

Ruby/moodBoard/app/views/comments/new.html.haml
%h1 New Comment
= render 'form'
= link_to 'Back', comments_path

Ruby/moodBoard/app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong Content:
  = @comment.content
%p
  %strong User:
  = @comment.user
%p
  %strong Design:
  = @comment.design
= link_to 'Edit', edit_comment_path(@comment)
|
= link_to 'Back', comments_path

Ruby/moodBoard/app/views/designs/_form.html.haml
= simple_form_for(@design) do |f|
  = f.error_notification
  .form-inputs
    = f.input :title
    = f.input :photo, as: :file
  .form-actions
    = f.button :submit

Ruby/moodBoard/app/views/designs/edit.html.haml
%h1 Editing Design
= render 'form'
= link_to 'Show', @design
|
= link_to 'Back', designs_path

Ruby/moodBoard/app/views/designs/index.html.haml
%p#notice= notice
%h1 Listing Designs
%table
  %thead
    %tr
      %th Title
      %th{:colspan => "3"}
  %tbody
    - @designs.each do |design|
      %tr
        %td= design.title
        %td= image_tag design.photo.url(:thumb)
        %td= link_to 'Show', design
        %td= link_to 'Edit', edit_design_path(design)
        %td= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Design', new_design_path

Ruby/moodBoard/app/views/designs/new.html.haml
%h1 New Design
= render 'form'
= link_to 'Back', designs_path

Ruby/moodBoard/app/views/designs/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @design.title
= link_to 'Edit', edit_design_path(@design)
|
= link_to 'Back', designs_path

Ruby/moodBoard/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MoodBoard
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

Ruby/moodBoard/app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :password
  .form-actions
    = f.button :submit

Ruby/moodBoard/app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

Ruby/moodBoard/app/views/users/index.html.haml
%p#notice= notice
%h1 Listing Users
%table
  %thead
    %tr
      %th Name
      %th Password
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

Ruby/moodBoard/app/views/users/new.html.haml
%h1 New User
= render 'form'
= link_to 'Back', users_path

Ruby/moodBoard/app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
%p
  %strong Password:
  = @user.password
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path