Ruby/dbc_overflow/config/routes.rb
Rails.application.routes.draw do

  get 'questions/index'
  root 'questions#index'

  resources :questions do
    resources :answers
  end

  resources :votes, only: [:create]

end

Ruby/dbc_overflow/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes

  def votes_count
    self.votes.select{|vote| vote.upvote }.count - self.votes.select{|vote| !vote.upvote}.count
  end

end

Ruby/dbc_overflow/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes

  def votes_count
    self.votes.select{|vote| vote.upvote }.count - self.votes.select{|vote| !vote.upvote}.count
  end

end

Ruby/dbc_overflow/app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many  :votes
end

Ruby/dbc_overflow/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  belongs_to :answer
end

Ruby/dbc_overflow/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  respond_to :html, :js
#index, show, new, edit, create, update

  def new
    @question = Question.find(params[:question_id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
  end

  private

    def answer_params
      params.require(:answer).permit(:content)
    end

end

Ruby/dbc_overflow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby/dbc_overflow/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  extend HTTParty
  respond_to :html,:js

  RANDOM_QUOTES = [
  "Use the digital SDD hard drive, then you can synthesize the digital pixel!",
  "Try to navigate the PNG microchip, maybe it will program the multi-byte alarm!",
  "transmitting the port won't do anything, we need to input the back-end THX capacitor!",
  "The JBOD circuit is down, override the optical feed so we can input the PNG matrix!",
  "We need to transmit the back-end EXE application!",
  "Use the solid state EXE system, then you can back up the mobile transmitter!",
  "The FTP application is down, hack the back-end pixel so we can connect the GB pixel!",
  "Try to synthesize the COM interface, maybe it will hack the primary driver!",
  "Try to generate the JBOD circuit, maybe it will connect the optical application!",
  "You can't transmit the panel without overriding the back-end PCI card!"]

  def index
    @questions = Question.all
    @quote = random_quote
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    #@question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    @question.save
    #flash[:notice] = "Your question was posted successfully"
    #redirect_to root_path
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    flash[:notice] = "Question updated"
    redirect_to @question
  end

  def destroy
    question = Question.find(params[:id])
    question.answers.destroy_all
    question.destroy
    flash[:notice] = "Question deleted"
    redirect_to root_path
  end

  private

    def random_quote
      auth = {:username => ENV['GITHUB_USERNAME'], :password => ENV['GITHUB_PASSWORD']}
      response = HTTParty.get('https://api.github.com/zen', basic_auth: auth)
      if response.code == 200
        response.body
      else
        RANDOM_QUOTES.sample
      end
    end

    def question_params
      params.require(:question).permit(:title, :content)
    end

end


#index, show, new, edit, create, update
#no new and still renders the new page. why?

Ruby/dbc_overflow/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

Ruby/dbc_overflow/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  respond_to :html, :js

  def create
    vote = Vote.create(vote_params)
    if vote.answer_id
      @voted_id = vote.answer_id
      @votes_count = Answer.find(@voted_id).votes_count
    elsif vote.question_id
      @voted_id = vote.question_id
      @votes_count = Question.find(@voted_id).votes_count
    end
  end

  private

    def vote_params
      params["vote"]["upvote"] == "1" ? params["vote"]["upvote"] = true : params["vote"]["upvote"] == false
      params.require(:vote).permit(:user_id, :question_id, :answer_id, :upvote)
    end

end

Ruby/dbc_overflow/app/helpers/answers_helper.rb
module AnswersHelper
end

Ruby/dbc_overflow/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/dbc_overflow/app/helpers/questions_helper.rb
module QuestionsHelper
end

Ruby/dbc_overflow/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/dbc_overflow/app/helpers/votes_helper.rb
module VotesHelper
end

Ruby/dbc_overflow/app/helpers/zen_api_helper.rb
# zen_api_helper.rb
module ZenApiHelper
  # def random_quote
  #   get('https://api.github.com/zen').body
  # end
end

Ruby/dbc_overflow/app/views/answers/_answer.erb
<p><%= answer.content %></p>
<%= form_for :vote, url: votes_path, method: :post, html: {id: "upvote-answer-#{answer.id}"}, remote: true do |f| %>
  <%= f.number_field :answer_id, value: answer.id, hidden: true %>
  <%= f.number_field :user_id, value: answer.user_id, hidden: true %>
  <%= f.text_field :upvote, value: "1", hidden: true %>
  <%= f.submit 'Nice!' %>
<% end %>
<%= form_for :vote, url: votes_path, method: :post, html: {id: "downvote-answer-#{answer.id}"}, remote: true do |f| %>
  <%= f.number_field :answer_id, value: answer.id, hidden: true %>
  <%= f.number_field :user_id, value: answer.user_id, hidden: true %>
  <%= f.text_field :upvote, value: "0", hidden: true %>
  <%= f.submit 'Buuuu' %>
<% end %>
<p>Votes count: <span id="votes-count-<%= answer.id %>"><%= answer.votes_count %></span></p>

Ruby/dbc_overflow/app/views/answers/_newanswer.html.erb
<%= form_for [@question, @question.answers.build], html: {id: 'new-answer-form'}, remote: true do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit 'Post answer'%>
  </p>
<% end %>

Ruby/dbc_overflow/app/views/answers/create.js.erb
$("#answers-list").append("<%= j (render @answer) %>");

Ruby/dbc_overflow/app/views/answers/new.js.erb
$("#new-answer-box").html("<%= j (render 'newanswer') %>");
$("#new-answer-box").slideToggle(200);

Ruby/dbc_overflow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ruby/dbc_overflow/app/views/questions/_newquestion.html.erb
<%= form_for :question, url: questions_path, html: {id: 'new-question-form'}, remote: true do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit 'Post question'%>
  </p>
<% end %>

Ruby/dbc_overflow/app/views/questions/_question.html.erb
<div>
  <p><%= question.title %></p>
  <p><%= question.content %></p>
  <p>Points: <span id ="votes-count-<%= question.id %>"><%= question.votes_count %></span></p>
  <%= link_to 'Check answers', question_path(question.id) %>
  <%= form_for :vote, url: votes_path, method: :post, html: {id: "upvote-question-#{question.id}"}, remote: true do |f| %>
    <%= f.number_field :question_id, value: question.id, hidden: true %>
    <%= f.number_field :user_id, value: question.user_id, hidden: true %>
    <%= f.text_field :upvote, value: "1", hidden: true %>
    <%= f.submit 'Nice!' %>
  <% end %>
  <%= form_for :vote, url: votes_path, method: :post, html: {id: "downvote-question-#{question.id}"}, remote: true do |f| %>
    <%= f.number_field :question_id, value: question.id, hidden: true %>
    <%= f.number_field :user_id, value: question.user_id, hidden: true %>
    <%= f.text_field :upvote, value: "0", hidden: true %>
    <%= f.submit 'Buuuu' %>
  <% end %>
</div>

Ruby/dbc_overflow/app/views/questions/create.js.erb
$("#questions-list").append("<%= j (render @question) %>");
$(".flash-notice").html("Your question was posted successfully");
setTimeout(function(){
  $(".flash-notice").empty();
},1500);

Ruby/dbc_overflow/app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit 'Update question'%>
  </p>
<% end %>

Ruby/dbc_overflow/app/views/questions/index.html.erb
<h1>Welcome!</h1>

<p>Quote of the day: <span id="zen-quote" style="color:green"><%= @quote %></span></p>

<h4 class="flash-notice" style="color:blue"></h4>

<%= link_to 'Post new question', new_question_path, remote: true %>

<div id="new-question-box" style="display:none"></div>

<h3>Here are the latest questions asked:</h3>

<div id="questions-list"><%= render @questions %></div>

Ruby/dbc_overflow/app/views/questions/new.js.erb
$('#new-question-box').html("<%= j (render 'newquestion' ) %>");
$('#new-question-box').slideToggle(200)

Ruby/dbc_overflow/app/views/questions/show.html.erb
<h4 style="color:blue"><%= flash[:notice] %></h4>

<h3>Question</h3>

<p><strong>Question: </strong><%= @question.title %></p>
<p><strong>Description: </strong><%= @question.content %></p>
<p><strong>Answers: </strong>
<div id="answers-list"><%= render @question.answers %></div>


<%= link_to 'Delete question', question_path(@question.id), method: :delete, data: {confirm: 'Are you sure?'} %>
<%= link_to 'Back', root_path %>

<br>
<%= link_to 'Post new answer', new_question_answer_path(@question.id), remote: true %>
<div id="new-answer-box" style="display:none"></div>

Ruby/dbc_overflow/app/views/votes/create.js.erb
$("#votes-count-<%= @voted_id %>").html("<%= @votes_count %>")